package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1



/**
 * Billingdetails generated by hbm2java
 */
public class Billingdetails  implements java.io.Serializable {


     private Integer id;
     private Invoices invoices;
     private Userdata userdata;
     private String fname;
     private String lname;
     private String email;
     private String address;
     private String city;
     private String country;
     private String mobile;

    public Billingdetails() {
    }

    public Billingdetails(Invoices invoices, Userdata userdata, String fname, String lname, String email, String address, String city, String country, String mobile) {
       this.invoices = invoices;
       this.userdata = userdata;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.address = address;
       this.city = city;
       this.country = country;
       this.mobile = mobile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoices getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Invoices invoices) {
        this.invoices = invoices;
    }
    public Userdata getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Userdata userdata) {
        this.userdata = userdata;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


