package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1



/**
 * InvoiceProducts generated by hbm2java
 */
public class InvoiceProducts  implements java.io.Serializable {


     private Integer id;
     private Invoices invoices;
     private Productdata productdata;
     private int qty;
     private String size;
     private double price;

    public InvoiceProducts() {
    }

    public InvoiceProducts(Invoices invoices, Productdata productdata, int qty, String size, double price) {
       this.invoices = invoices;
       this.productdata = productdata;
       this.qty = qty;
       this.size = size;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoices getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Invoices invoices) {
        this.invoices = invoices;
    }
    public Productdata getProductdata() {
        return this.productdata;
    }
    
    public void setProductdata(Productdata productdata) {
        this.productdata = productdata;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


