package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoices generated by hbm2java
 */
public class Invoices  implements java.io.Serializable {


     private Integer id;
     private Userdata userdata;
     private String date;
     private double totalPrice;
     private Set invoiceProductses = new HashSet(0);
     private Set billingdetailses = new HashSet(0);

    public Invoices() {
    }

	
    public Invoices(Userdata userdata, String date, double totalPrice) {
        this.userdata = userdata;
        this.date = date;
        this.totalPrice = totalPrice;
    }
    public Invoices(Userdata userdata, String date, double totalPrice, Set invoiceProductses, Set billingdetailses) {
       this.userdata = userdata;
       this.date = date;
       this.totalPrice = totalPrice;
       this.invoiceProductses = invoiceProductses;
       this.billingdetailses = billingdetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Userdata getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Userdata userdata) {
        this.userdata = userdata;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Set getInvoiceProductses() {
        return this.invoiceProductses;
    }
    
    public void setInvoiceProductses(Set invoiceProductses) {
        this.invoiceProductses = invoiceProductses;
    }
    public Set getBillingdetailses() {
        return this.billingdetailses;
    }
    
    public void setBillingdetailses(Set billingdetailses) {
        this.billingdetailses = billingdetailses;
    }




}


