package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1



/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer id;
     private Userdata userdata;
     private String title;
     private String description;
     private String image;
     private String date;

    public Posts() {
    }

    public Posts(Userdata userdata, String title, String description, String image, String date) {
       this.userdata = userdata;
       this.title = title;
       this.description = description;
       this.image = image;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Userdata getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Userdata userdata) {
        this.userdata = userdata;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


