package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1



/**
 * Reviews generated by hbm2java
 */
public class Reviews  implements java.io.Serializable {


     private Integer id;
     private Productdata productdata;
     private Userdata userdata;
     private String review;

    public Reviews() {
    }

    public Reviews(Productdata productdata, Userdata userdata, String review) {
       this.productdata = productdata;
       this.userdata = userdata;
       this.review = review;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Productdata getProductdata() {
        return this.productdata;
    }
    
    public void setProductdata(Productdata productdata) {
        this.productdata = productdata;
    }
    public Userdata getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Userdata userdata) {
        this.userdata = userdata;
    }
    public String getReview() {
        return this.review;
    }
    
    public void setReview(String review) {
        this.review = review;
    }




}


