package ORM;
// Generated May 23, 2021 12:57:40 AM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer number;
     private Productdata productdata;
     private Userdata userdata;
     private String size;
     private int quantity;

    public Wishlist() {
    }

    public Wishlist(Productdata productdata, Userdata userdata, String size, int quantity) {
       this.productdata = productdata;
       this.userdata = userdata;
       this.size = size;
       this.quantity = quantity;
    }
   
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Productdata getProductdata() {
        return this.productdata;
    }
    
    public void setProductdata(Productdata productdata) {
        this.productdata = productdata;
    }
    public Userdata getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Userdata userdata) {
        this.userdata = userdata;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


